### ISSUE TITLE
GPG smartcard (Yubikey) support is broken

### ISSUE THREAD

**Issue by taaem** [flathub/org.gnome.Evolution#19] opened 2019-12-19 22:52 UTC
Evolution Flatpak is not able to see my Smartcard (Yubikey) and it just asks for the device to be plugged in.

Possibly this can be fixed with: https://github.com/flathub/org.mozilla.Thunderbird/issues/51

**Comment by ispanos** [comment] 2020-04-01 23:04
Can you try `flatpak run --device=all org.gnome.Evolution` and see if it works?

**Comment by taaem** [comment] 2020-04-03 11:01
@ispanos Sadly it doesn't work, I get a prompt to insert my smartcard which I do and then nothing happens.

**Comment by taaem** [comment] 2020-04-03 11:41
I suppose there is also the pcsc-lite program missing, because gpg is using that to contact the smartcard. I have it on the host but according to the linked thunderbird issue you also need it inside the flatpak.

**Comment by Sesivany** [comment] 2020-04-21 12:35
Duplicate of #16

**Closed by Sesivany** 2020-04-21 12:35 UTC
