### ISSUE TITLE
Not recieving GNOME notifications from flatpak

### ISSUE THREAD

**Issue by Minter1** [flathub/org.gnome.Evolution#29] opened 2020-05-01 13:58 UTC
I am running F32 silverblue (GNOME 3.36.1) and have the Evolution flatpak installed. I have noted that the calendar or task notifications are not being passed through to the GNOME notifications list or calendar section of this drop down panel. I am unsure about emails because I don't use this feature.

**Comment by Sesivany** [comment] 2020-05-19 13:30
Evolution in Flatpak is pretty much self-contained, it doesn't share email, calendar, or task information with the host. It only integrates with GNOME Online Accounts, so if you have an account there Evolution loads the credentials and logs in, but that's it.
Calendar and task information only appears in the panel if you use an account with online syncing and both evolution-data-server in the flatpak and evolution-data-server on the host are connected to it via GOA.
This is an intended behaviour, we don't wanna rely on the host e-d-s because then the Evolution flatpak would depent on the underlying OS, so I'm closing this one as wontfix.

**Closed by Sesivany** 2020-05-19 13:30 UTC
Labels: wontfix
