### ISSUE TITLE
Copy-paste hangs other applications 

### ISSUE THREAD

**Issue by zsdedan** [flathub/org.gnome.Evolution#50] opened 2021-07-01 08:23 UTC
I do not know whether to write a bug report here, but I think it will not be superfluous if the developers consider it.
I use google translate. 

There are times when I copy text from an evolution, paste it into another application and it freezes or does not respond for a long time. 

For example, when I paste text into LibreOffice Writer, the following message appears "Requested Clipboard format is not available".

Firefox hangs until it is restarted. 

Helps to kill all processes associated with evolution and restart the application. After that, the text is copied from evolution for a while normally. 

Evolution 3.40.2 (by Flathub.org) 
Ubuntu 21.04
Display server Wayland

**Comment by Sesivany** [comment] 2021-07-07 17:27
This issue is very unlikely related to Flatpak. It's most likely an issue with Wayland clipboard on your distribution. We can't reproduce it on Fedora. If you wanna debug it with Evolution developers, please [open a ticket upstream](https://gitlab.gnome.org/GNOME/evolution/-/issues). I'm closing it here because we keep this tracker for flatpak-related issues.

**Closed by Sesivany** 2021-07-07 17:27 UTC
