### ISSUE TITLE
UI can't be resized/rearanged, checkboxes not preserving values

### ISSUE THREAD

**Issue by krashekspres** [flathub/org.gnome.Evolution#1] opened 2018-10-03 13:24 UTC
So I had to try it right away :)
Emails, calendar and todo are working. But UI can't be resized nor I am able to change anything regarding UI (probably dconf error).

Log output:
(evolution.bin:47): dconf-WARNING **: 15:22:02.963: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files

**Comment by Sesivany** [comment] 2018-10-03 15:18
Thank you for the report. We turned on an access to the host dconf in the last minute because we were told it would otherwise break theming, icons etc. for GTK 3.
The problem is that Evolution runs its own dbus session within the sandbox to bridge communication with the host evolution-data-server. Even after I set forwarding dbus calls to dconf it doesn't work.
We're looking into it, hold on.

**Comment by ahayzen** [comment] 2018-10-03 19:33
You probably already know but the existing wrapper script fails to start dconf (as it was removed), so outputs an error in the console. If you do go down the route of using the hosts dconf this line [0] should probably be removed.

Error shown in the console.
`/app/bin/evolution-wrapper: line 4: /app/libexec/dconf-service: No such file or directory`

0 - https://github.com/flathub/org.gnome.Evolution/blob/master/org.gnome.Evolution.json#L295

**Comment by Sesivany** [comment] 2018-10-04 13:08
Should be fixed with the update I committed roughly an hour ago. Once it's available, please update the flatpak and confirm that it has fixed the issue for you.

**Comment by krashekspres** [comment] 2018-10-04 13:28
It's fixed in the latest version. Thank you.

Cheers,
D.

**Closed** 2018-10-04 13:29 UTC
Labels: bug
