### ISSUE TITLE
Evolution blocks shutdown for 90 seconds if it is running

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.gnome.Evolution#15] opened 2019-09-13 21:12 UTC
# What happened:
1) Update to Evolution 3.34
2) Launch Evolution
3) While Evolution is running shutdown the computer
4) Notice that shutdown takes a long time (blocks for 90 seconds)

# What I expected to happen:
At step 4 for the system to shutdown normally.

# Logs
Looking at the journal, Evolution is the last user session item to be killed, and it takes 90 seconds for it to be shutdown, with the final shutdown being a forced one due to a timeout.

```
Sep 13 21:30:48 Thinkpad-T480 systemd[2576]: Stopping flatpak-org.gnome.Evolution-3969.scope.
...
Sep 13 21:32:19 Thinkpad-T480 systemd[2576]: flatpak-org.gnome.Evolution-3969.scope: Stopping timed out. Killing.
Sep 13 21:32:19 Thinkpad-T480 systemd[2576]: flatpak-org.gnome.Evolution-3969.scope: Killing process 3986 (bwrap) with signal SIGKILL.
Sep 13 21:32:19 Thinkpad-T480 systemd[2576]: flatpak-org.gnome.Evolution-3969.scope: Killing process 4022 (evolution-addre) with signal SIGKILL.
Sep 13 21:32:19 Thinkpad-T480 systemd[2576]: flatpak-org.gnome.Evolution-3969.scope: Failed with result 'timeout'.
Sep 13 21:32:19 Thinkpad-T480 systemd[2576]: Stopped flatpak-org.gnome.Evolution-3969.scope.
Sep 13 21:32:19 Thinkpad-T480 systemd[2576]: Reached target Shutdown.
Sep 13 21:32:19 Thinkpad-T480 systemd[2576]: systemd-exit.service: Succeeded.
Sep 13 21:32:19 Thinkpad-T480 systemd[2576]: Started Exit the Session.
Sep 13 21:32:19 Thinkpad-T480 systemd[2576]: Reached target Exit the Session.
```

# Version
```
$ lsb_release -rd
Description:    Debian GNU/Linux 10 (buster)
Release:        10
$ apt policy flatpak
flatpak:
  Installed: 1.2.4-1
  Candidate: 1.2.4-1
  Version table:
 *** 1.2.4-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
$ flatpak info org.gnome.Evolution

Evolution - Manage your e-mail, contacts and schedule

          ID: org.gnome.Evolution
         Ref: app/org.gnome.Evolution/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.34.0  (by Flathub.org)
     License: GPL-2.0+ and GFDL-1.3
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 38.1 MB
     Runtime: org.gnome.Platform/x86_64/3.32
         Sdk: org.gnome.Sdk/x86_64/3.32

      Commit: f6513eef9c65aa74dd9f68aec3b0ecd8b171a0735525651cfcc59fbde9a2ebfe
      Parent: 3aee026540749397d2d878ec7d46c0d3cc8fab0ae7ea3a69085d9916cd56ee44
     Subject: Update to 3.34 (fixed syntax) (52a61960)
        Date: 2019-09-12 08:48:57 +0000
```

**Comment by Sesivany** [comment] 2020-04-21 12:28
We can't reproduce this, are you still experiencing this problem?

**Comment by ahayzen** [comment] 2020-04-21 21:43
I've not seen this recently (or at all with 3.36 I think), so I'll close for now :-)

**Comment by ahayzen** [comment] 2020-06-23 21:17
This has started happening again on multiple machines, I've caught hopefully more useful information. I wonder if it is related to leaving Evolution running when suspending a resuming the session (note sometimes my WiFi takes a bit to reappear after resume etc if that affects things).

I have generated these logs by using `grep -i -E "reboot|evolution|systemd-sleep"` over the previous system log and taking everything from when the first flatpak related evolution is started and the system is shutdown. Please let me know if there you need more of the syslog or if there is any debugging I can enable for when it happens again.

Here appears to be where I have started the Evolution instance.
```
Jun 22 08:08:04 Thinkpad-T480 polkitd(authority=local)[1163]: Registered Authentication Agent for unix-process:4396:9318 (system bus name :1.618 [/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=evolution org.gnome.Evolution -c current], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_GB.UTF-8)
Jun 22 08:08:04 Thinkpad-T480 systemd[3498]: Started flatpak-org.gnome.Evolution-4396.scope.
Jun 22 08:08:05 Thinkpad-T480 evolution.bin[4463]: Failed to add service 'Sendmail' (sendmail): No provider available for protocol “sendmail”
```
Here we suspend and resume the system twice, note an error on the second resume from Evolution.
```
Jun 22 20:19:04 Thinkpad-T480 systemd-sleep[17525]: Suspending system...
Jun 23 09:55:34 Thinkpad-T480 systemd-sleep[17525]: System resumed.
Jun 23 19:08:23 Thinkpad-T480 systemd-sleep[26167]: Suspending system...
Jun 23 21:51:23 Thinkpad-T480 systemd-sleep[26167]: System resumed.
Jun 23 21:51:44 Thinkpad-T480 evolution.bin[4463]: Your application did not unregister from D-Bus before destruction. Consider using g_application_run().
```
Here we request a reboot of the system.
```
Jun 23 21:53:35 Thinkpad-T480 systemd-logind[1092]: System is rebooting.
Jun 23 21:53:35 Thinkpad-T480 evolution-calen[4454]: Error releasing name org.gnome.Evolution.org.gnome.evolution.dataserver.Calendar8: The connection is closed
Jun 23 21:53:35 Thinkpad-T480 evolution-addre[4439]: Error releasing name org.gnome.Evolution.org.gnome.evolution.dataserver.AddressBook10: The connection is closed
Jun 23 21:53:35 Thinkpad-T480 evolution-addre[4439]: Source ID 1 was not found when attempting to remove it
Jun 23 21:53:35 Thinkpad-T480 evolution-addre[4439]: Source ID 2 was not found when attempting to remove it
Jun 23 21:53:35 Thinkpad-T480 evolution-addre[4439]: Error setting property 'ConnectionStatus' on interface org.gnome.evolution.dataserver.Source: The connection is closed (g-io-error-quark, 18)
Jun 23 21:53:35 Thinkpad-T480 evolution-calen[4454]: (src/libebackend/e-data-factory.c:1374):data_factory_backend_toggle_notify_cb: code should not be reached
Jun 23 21:53:35 Thinkpad-T480 evolution-sourc[4425]: Error releasing name org.gnome.Evolution.org.gnome.evolution.dataserver.Sources5: The connection is closed
Jun 23 21:53:35 Thinkpad-T480 evolution-sourc[4425]: Source ID 2 was not found when attempting to remove it
Jun 23 21:53:35 Thinkpad-T480 evolution-sourc[4425]: Source ID 3 was not found when attempting to remove it
Jun 23 21:53:35 Thinkpad-T480 evolution-sourc[4425]: Error while sending AddMatch() message: The connection is closed
Jun 23 21:53:35 Thinkpad-T480 evolution-sourc[4425]: Error while sending AddMatch() message: The connection is closed
Jun 23 21:53:35 Thinkpad-T480 evolution-sourc[4425]: Unable to connect to the GNOME Online Accounts service: Error calling StartServiceByName for org.gnome.OnlineAccounts: The connection is closed
Jun 23 21:53:36 Thinkpad-T480 systemd[1]: Starting Show Plymouth Reboot Screen...
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: Stopping Evolution source registry...
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: Stopping flatpak-org.gnome.Evolution-4396.scope.
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: Stopping Evolution calendar service...
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: Stopping Evolution address book service...
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: evolution-source-registry.service: Succeeded.
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: Stopped Evolution source registry.
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: evolution-calendar-factory.service: Succeeded.
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: Stopped Evolution calendar service.
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: evolution-addressbook-factory.service: Succeeded.
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: Stopped Evolution address book service.
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: reboot-notifier-gui.path: Succeeded.
Jun 23 21:53:36 Thinkpad-T480 systemd[3498]: Stopped Reboot Notifier GUI Check.
Jun 23 21:53:36 Thinkpad-T480 systemd[1]: Started Show Plymouth Reboot Screen.
```
Notice how we wait 90 seconds here for Evolution to be killed.
```
Jun 23 21:55:06 Thinkpad-T480 systemd[3498]: flatpak-org.gnome.Evolution-4396.scope: Stopping timed out. Killing.
Jun 23 21:55:06 Thinkpad-T480 systemd[3498]: flatpak-org.gnome.Evolution-4396.scope: Killing process 4409 (bwrap) with signal SIGKILL.
Jun 23 21:55:06 Thinkpad-T480 systemd[3498]: flatpak-org.gnome.Evolution-4396.scope: Killing process 4454 (evolution-calen) with signal SIGKILL.
Jun 23 21:55:06 Thinkpad-T480 systemd[3498]: flatpak-org.gnome.Evolution-4396.scope: Failed with result 'timeout'.
Jun 23 21:55:06 Thinkpad-T480 systemd[3498]: Stopped flatpak-org.gnome.Evolution-4396.scope.
Jun 23 21:55:11 Thinkpad-T480 systemd[1]: systemd-reboot.service: Succeeded.
Jun 23 21:55:11 Thinkpad-T480 systemd[1]: Started Reboot.
Jun 23 21:55:11 Thinkpad-T480 systemd[1]: Reached target Reboot.
```

**Comment by Sesivany** [comment] 2023-06-15 11:53
This is a bug reported 4 years ago we cannot reproduce, thus I'm closing it. If you're still experiencing it, feel free to reopen it.

**Closed by Sesivany** 2023-06-15 11:53 UTC
