### ISSUE TITLE
3.38.2 update data server failures

### ISSUE THREAD

**Issue by CarlPerkins** [flathub/org.gnome.Evolution#45] opened 2020-11-20 20:20 UTC
installed update 3.38.2 release 11.20, resulted in:

>The memo list backend servicing “Personal” has quit unexpectedly.

Some of your memos may not be available until Evolution is restarted.

>Failed to open calendar “On This Computer : Personal”

Unable to connect to “Personal”: Message recipient disconnected from message bus without replying

>The task list backend servicing “Personal” has quit unexpectedly.

Some of your tasks may not be available until Evolution is restarted.

>Error creating view for the calendar “Birthdays & Anniversaries”

Cannot invoke method; proxy is for the well-known name org.gnome.Evolution.org.gnome.evolution.dataserver.Calendar8 without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag

restart failed to solve.
new calendar items fail

**Comment by Sesivany** [comment] 2020-11-20 21:45
You don't have any other instance of Evolution running on the system, do you?

**Comment by Sesivany** [comment] 2020-11-20 21:49
I can't reproduce it here. It may be related to removing the dconf access workaround.

**Comment by CarlPerkins** [comment] 2020-11-20 22:37
nope. just an update to original instance
not familiar with the dconf access workaround

**Comment by Sesivany** [comment] 2020-11-23 11:45
It seems like the calendar factory crashed for some reason.

To debug it, try running:
`flatpak run --devel --command=sh org.gnome.Evolution`
`/app/libexec/evolution-source-registry & gdb /app/libexec/evolution-calendar-factory --ex "r -w" --ex bt`

And then in another terminal run:
`flatpak run org.gnome.Evolution`

If it crashes again, you should get some info about the crash.

Also what OS do you use? Because you may be hitting this problem:
https://github.com/libical/libical/issues/454
https://gitlab.gnome.org/GNOME/evolution-data-server/-/issues/267

**Comment by CarlPerkins** [comment] 2020-11-25 18:30
using Ubuntu flavored POP! (System76) for this instance of Evolution.
functioned error-free prior to installing update to 3.38.2
debug result: 
===
error: app/org.gnome.Evolution/app/libexec not installed
Command 'gdb' not found
===

other terminal resulted in:
===
Gtk-Message: 10:28:30.462: Failed to load module "appmenu-gtk-module"
Gtk-Message: 10:28:30.504: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:28:30.504: Failed to load module "canberra-gtk-module"

(evolution.bin:26): GLib-GIO-WARNING **: 10:28:30.605: Your application did not unregister from D-Bus before destruction. Consider using g_application_run().
===
thanks for the attention. any other thoughts?

**Comment by Sesivany** [comment] 2020-11-26 11:04
Could it possibly be this issue? https://gitlab.gnome.org/GNOME/evolution/-/issues/1232

**Comment by Sesivany** [comment] 2020-11-26 15:36
In the beta channel I just published Evolution 3.38.2 with libical from master which has some fixes that may help with the tzdata issue you're probably experiencing. Could you please try installing it and let me know if it helps?
 
flatpak install https://flathub.org/beta-repo/appstream/org.gnome.Evolution.flatpakref

**Comment by CarlPerkins** [comment] 2020-12-01 17:46
thanks for your continued attention.
determining whether it's an OS or flatpak version issue is beyond my skill set. reading through the gnome string you sent, the issues and error messages don't sync with mine. everything works fine except the calendar and memos. those features don't crash, they just have no data and throw errors that are documented up top. 
i'm not clear on how to install from the link you provided.
kinda inclined at this point to do data backup and revert to prior version where i had no issues.

**Comment by michel-slm** [comment] 2020-12-14 20:42
I'm getting the same errors on CentOS 8.3, and also - under some unclear circumstances Evolution would just crash with a segfault if I start it in the calendar view (and pkill evolution + flatpak kill org.gnome.Evolution or even rebooting don't fix it).

Switching to the beta fixes the issue, it seems.

Running GNOME so the following processes are automatically started

```
~ 
❯ rpm -qa 'evolution*'          
evolution-data-server-langpacks-3.28.5-14.el8.noarch
evolution-data-server-3.28.5-14.el8.x86_64

~ 
❯ ps auxwww | grep evolution
michel     10431  0.0  0.2 1055832 29300 ?       Ssl  12:32   0:00 /usr/libexec/evolution-calendar-factory
michel     10436  0.0  0.2 1199048 40016 ?       Ssl  12:32   0:00 /usr/libexec/evolution-source-registry
michel     10445  0.0  0.3 2121792 45044 ?       Sl   12:32   0:00 /usr/libexec/evolution-calendar-factory-subprocess --factory all --bus-name org.gnome.evolution.dataserver.Subprocess.Backend.Calendarx10431x2 --own-path /org/gnome/evolution/dataserver/Subprocess/Backend/Calendar/10431/2
michel     10455  0.0  0.2 1042372 30476 ?       Ssl  12:32   0:00 /usr/libexec/evolution-addressbook-factory
michel     10471  0.0  0.2 1324752 29436 ?       Sl   12:32   0:00 /usr/libexec/evolution-addressbook-factory-subprocess --factory all --bus-name org.gnome.evolution.dataserver.Subprocess.Backend.AddressBookx10455x2 --own-path /org/gnome/evolution/dataserver/Subprocess/Backend/AddressBook/10455/2
michel     13612  0.0  0.0  17656  1232 pts/0    S+   12:39   0:00 bwrap --args 32 evolution --offline
michel     13623  0.0  0.0  17920  1116 pts/0    S+   12:39   0:00 bwrap --args 32 evolution --offline
michel     13624  0.0  0.0   7568  4052 pts/0    S+   12:39   0:00 /bin/sh /app/bin/evolution --offline
michel     13637  4.6  0.8 1284040 120060 pts/0  SLl+ 12:39   0:06 /app/libexec/evolution-source-registry
michel     13652  4.2  0.5 736316 81720 pts/0    Sl+  12:39   0:05 /app/libexec/evolution-addressbook-factory -r
michel     13668  6.0  0.8 2725204 113280 pts/0  Sl+  12:39   0:08 /app/libexec/evolution-calendar-factory -r
michel     13677  8.7  1.5 104126616 224232 pts/0 SLl+ 12:39   0:11 /app/bin/evolution.bin --offline
michel     13694  4.7  1.3 1478748 191880 pts/0  Sl+  12:39   0:06 /app/libexec/evolution-data-server/evolution-alarm-notify
michel     14535  0.0  0.0 221904  1084 pts/1    S+   12:42   0:00 grep --color=auto evolution
```

**Comment by CarlPerkins** [comment] 2021-01-08 16:48
ka-ching! switch to master libical in 3.38.3 solved my issues. not going to close the string in case others still having pains.
again, thanks very much to everyone for the attention and effort. really like the product. hope your new year is safe and sane as possible. peace!

**Comment by Sesivany** [comment] 2021-02-04 10:45
Seems to be fixed with the latest update, closing...

**Closed by Sesivany** 2021-02-04 10:45 UTC
Labels: bug, question
