### ISSUE TITLE
Can not open mail attachments

### ISSUE THREAD

**Issue by mczimmermann** [flathub/org.gnome.Evolution#6] opened 2018-10-17 07:52 UTC
When I try to open a mail attachment, e.g., a pdf file, I just get a timeout error instead of a dialog to select a program to open the attachment.

**Comment by Sesivany** [comment] 2018-10-18 11:41
The problem is that Evolution doesn't use the OpenURI portal for this. I've opened a [bug](https://gitlab.gnome.org/GNOME/evolution/issues/189) about it upstream. As a workaround you can save the file to your home and open it from a file browser.

**Comment by fansari** [comment] 2018-11-11 20:48
I noticed the same issue. The rpm based version does not have this problem.

**Comment by Sesivany** [comment] 2018-12-11 14:08
This should be now fixed with the 3.30.3 version.

**Closed by Sesivany** 2018-12-11 14:08 UTC
Labels: bug, upstream
