### ISSUE TITLE
EteSync support 

### ISSUE THREAD

**Issue by snaggen** [flathub/org.gnome.Evolution#38] opened 2020-09-22 07:54 UTC
Now that there is a evolution etesync plugin,it would be nice to have it included in the flathub build.
https://gitlab.gnome.org/nourmat/evolution-etesync/

**Comment by Sesivany** [comment] 2020-09-24 10:05
It's definitely on our radar. We'll try to bring it with the next regular update.

**Comment by tasn** [comment] 2020-09-25 06:24
Great to hear, and happy to assist if you need anything (EteSync developer here).
Btw, Nour (who created this module) is in the process of migrating it to the [next version of the protocol](https://blog.etesync.com/etesync-2-0-ready-for-testers/) which should come out of beta soon. It should be ready in the next few weeks, so keep an eye out for updates. It'll just replace master in the repo linked to by @snaggen.

**Comment by Sesivany** [comment] 2020-09-25 18:28
I learned today that the library the plugin depends on is written in Rust. I'll have to look around and figure out what's the best way to build it. I haven't built any Rust content on Flathub yet.

**Comment by tasn** [comment] 2020-09-26 15:10
Yeah, it is. I'm not familiar with Flathub, but happy to help with any way I can. Essentially, all you need is to have cargo (and OpenSSL as a dep) available, and then building is a breeze. How does building a C project work on flathub? I bet things aren't that different.

**Comment by Sesivany** [comment] 2020-09-29 16:40
I looked at it today, but I got stuck on Cargo pulling in dependencies from the Internet on build time. Flatpak building is offline, so it fails. I guess there is some workaround, I'll look around, but I don't know when I'll be able to get back to it again, I've been pretty busy lately. So if anyone is interested, merge requests are welcome.

This is what I've got so far:
{
                "name": "libetesync",
                "buildsystem": "simple",
                "no-autogen": true,
                "build-options" : { 
                    "append-path": "/usr/lib/sdk/rust-stable/bin"
                    },
                "sources": [
            	    {
            	        "type": "archive",
            	        "url": "https://github.com/etesync/etebase-rs/archive/legacy.zip",
            	        "sha256": "8f4c5878b84384d758af40dee04dfc85c362d6b4a82ea54bf57ad79509588b7b"
            	    }
            	 ],
            	"build-commands": [
            	    "cargo build"
            	    ]
            },

**Comment by tasn** [comment] 2020-09-30 11:47
I know nothing about flatkpak, so take it with a grain of salt, but it seems quite solvable:
Take a look at: https://belmoussaoui.com/article/8-how-to-flatpak-a-rust-application
You can enable network access during build using:
```
        "build-args" : [
            "--share=network"
        ],
```
You can also use the Rust sdk extension to easily have rust available.

Take a look at that post, it looks like it's actually quite easy.

**Comment by Sesivany** [comment] 2020-10-02 16:06
I also found a script in the flathub helpers repo that checks the Cargo config file and downloads and installs the dependencies before building. Either way should work. Now I'm waiting for the new version of the plugin which uses the new API and library, then I'll include it.

**Comment by tasn** [comment] 2020-10-02 16:10
That's cool! Could you please share the link (in case I'd need it in the future).
I chatted with the developer of the plugin today and the module is complete. I'll help him test it in the next few days and then it should be ready. Btw, the dependency for the new version of the plugin is https://github.com/etesync/libetebase rather than libetesync. Just FYI.

**Comment by tasn** [comment] 2020-10-21 14:01
I tested it, and it's looking good! The maintainer of Evolution and I'll will be reviewing it for the next few days and merge it into the main GNOME repository for the evolution-etesync module: https://gitlab.gnome.org/GNOME/evolution-etesync

**Comment by tasn** [comment] 2020-11-30 13:52
It's finally been merged into master, and a new release has been made! \o/

**Comment by Sesivany** [comment] 2020-12-01 16:39
Great news!
Sadly I haven't made any progress. I tried enabling network during build time, but I hit errors resolving the cargo index addresses in the flatpak builder while it works on the host. Not sure where the problem could be, perhaps a bug with address resolving in the used runtime.
I'll keep digging, but I must admit I haven't had much time for it lately, if someone makes it work with the runtime we're using for Evolution, merge requests are welcome.

**Comment by tasn** [comment] 2020-12-01 16:42
Cool, thanks the update! I wonder if there's a different way of doing it. Maybe even just including a pre-built version from a distro like Archlinux? (already in the repos)

**Comment by Sesivany** [comment] 2020-12-01 16:56
Yes, there is. You can download cargo dependencies before the build and provide them as build modules during the build. There is [some support](https://github.com/flatpak/flatpak-builder-tools/pull/52) for it in master of flatpak-builder, but not available in the stable version, so we'd need something custom. I'll take a look at it more if the way with network enabled fails.

**Comment by bilelmoussaoui** [comment] 2020-12-01 17:52
I will have a look at this one tomorrow

**Comment by tasn** [comment] 2020-12-10 09:46
Hey @bilelmoussaoui, did you get a chance to look at it? Anything you need from me?

**Comment by tasn** [comment] 2021-01-10 20:55
Happy new year everyone!

Just following up on my previous message to see if there's anything I can do to help make this happen. Users have been asking for this, so it would be great to have it!

**Comment by Sesivany** [comment] 2021-02-10 17:09
I now build the testing Evolution in the beta channel with the etesync plugin, but while testing I fail to find how to add an etesync account.
You can test it too: https://flathub.org/beta-repo/appstream/org.gnome.Evolution.flatpakref
I'll follow up with the lead Evo developer.

**Comment by tasn** [comment] 2021-02-10 17:52
You got the right deps? It should just show there in the main lookup page where you put in your username + server. Maybe it's because you don't have an etesync account? Maybe try `demo_user` as the user?

**Comment by Sesivany** [comment] 2021-02-11 15:21
Milan also tested it for me and it seems to be working as intended. I'll include it in tomorrow's stable update.

**Comment by tasn** [comment] 2021-02-11 15:26
Yay! :tada: :tada: :tada:

**Comment by Sesivany** [comment] 2021-02-12 13:55
The stable version of Evolution with Etesync plugin included has been shipped today, so I'm closing the ticket.

**Closed by Sesivany** 2021-02-12 13:55 UTC
Labels: enhancement
