### ISSUE TITLE
Office365 OAuth2 doesn't work in flatpak

### ISSUE THREAD

**Issue by jacobzimmermann** [flathub/org.gnome.Evolution#48] opened 2021-04-18 21:28 UTC
When trying to set up an Office365 email account in Evolution 3.38 (which requires overriding the application ID and tenant ID), I can't get past the authentication page. After entering my credentials and confirming with an Okta push, I always get immediately sent back to the first screen (username).

The same procedure works perfectly in Evolution 3.38 installed from the RPM repository. As far as I can tell the situation is the same with Evolution 3.40.

I'm not at all familiar with Evolution's debugging or troubleshooting options but please let me know if I can produce a log or some other information that may help diagnosing the problem.

**Comment by Sesivany** [comment] 2021-04-19 14:14
Thank you for reporting the issue. [It's already been reported upstream](https://gitlab.gnome.org/GNOME/libsecret/-/issues/62) and it seems like an issue in libsecret. Unfortunately, until it is fixed there I can't do much about it, even going back to the GNOME 3.38 runtime wouldn't help.

**Comment by Sesivany** [comment] 2021-12-13 20:02
It should be fixed with the latest release. Can you verify if it's fixed?

**Comment by chase9** [comment] 2021-12-16 20:33
Doesn't look like this is fixed. I still see issues with being unable to authenticate against Office365. Running gnome-keyring-daemon in the foreground I see this line when trying to authenticate:
`asked to register item /org/freedesktop/secrets/collection/login/<NUM>, but it's already registered`
Where <NUM> is the entry #.

It looks like the refresh token is saved properly but not being read.

**Comment by chase9** [comment] 2021-12-23 13:44
This morning I launched Evolution and everything seems to be working properly. Nothing changed on my end AFAIK

**Comment by catagris** [comment] 2022-04-22 04:12
I am also having this issue, I have tried my own application and the two application IDs found here: https://wiki.gnome.org/Apps/Evolution/EWS/OAuth2

I get this redirect but the login page just appears again and again.
![Broken Login](https://user-images.githubusercontent.com/1514273/164599040-f45ad501-099a-4da3-a531-acd427881213.png)

**Comment by gdonval** [comment] 2022-10-31 16:33
Just to say I cannot reproduce the bug (I am not a package maintainer): OAuth2 works for me in this flatpak to connect to an Office365 email account.

**Comment by Sesivany** [comment] 2023-06-15 10:54
This problem doesn't seem to occur any more, closing.

**Closed by Sesivany** 2023-06-15 10:54 UTC
Labels: bug, upstream
